openapi: 3.0.3
info:
  title: OpenAPI schema for template aws-rds
components:
  schemas:
    variables:
      type: object
      required:
      - architecture
      - engine
      - password
      properties:
        engine:
          title: Engine
          type: string
          description: Select the RDS engine, support serval kinds of 'MySQL', 'MariaDB'
            and 'PostgreSQL'.
          enum:
          - MySQL-5.7
          - MySQL-8.0
          - MariaDB-10.3
          - MariaDB-10.4
          - MariaDB-10.5
          - MariaDB-10.6
          - PostgreSQL-13
          - PostgreSQL-14
          - PostgreSQL-15
          x-walrus-ui:
            group: Basic
        architecture:
          title: Architecture
          type: string
          description: Select the RDS architecture, support from 'Standalone' and
            'Replication'.
          enum:
          - Standalone
          - Replication
          x-walrus-ui:
            group: Basic
        password:
          title: Password
          type: string
          description: Specify the root password to initialize after launching.
          writeOnly: true
          format: password
          x-walrus-ui:
            group: Basic
        username:
          title: Username
          type: string
          default: rdsusr
          description: Specify the root username to initialize after launching.
          x-walrus-ui:
            group: Basic
        database:
          title: Database
          type: string
          default: rdsdb
          description: Specify the database name to initialize after launching.
          x-walrus-ui:
            group: Basic
        instance_type:
          title: Instance Type
          type: string
          default: ''
          description: Specify the instance type to deploy the RDS engine, pick burstable
            2C4G type automatically if empty.
          x-walrus-ui:
            group: Advanced
        storage_type:
          title: Storage Type
          type: string
          default: ''
          description: Specify the storage type to deploy the RDS engine, pick GP2
            if empty.
          x-walrus-ui:
            group: Advanced
        init_sql_url:
          title: Init SQL URL
          type: string
          default: ''
          description: Specify the init SQL download URL to initialize after launching.
          x-walrus-ui:
            group: Advanced
        publicly_accessible:
          title: Publicly Accessible
          type: boolean
          default: false
          description: Specify to allow publicly accessing.
          x-walrus-ui:
            group: Advanced
        vpc_id:
          title: VPC ID
          type: string
          default: ''
          description: Specify the existing VPC ID to deploy, create a new one if
            empty.
          x-walrus-ui:
            group: Advanced
        walrus_metadata_environment_name:
          title: walrus_metadata_environment_name
          type: string
          default: ''
          description: Walrus metadata environment name.
          x-walrus-ui:
            hidden: true
        walrus_metadata_project_name:
          title: walrus_metadata_project_name
          type: string
          default: ''
          description: Walrus metadata project name.
          x-walrus-ui:
            hidden: true
        walrus_metadata_service_name:
          title: walrus_metadata_service_name
          type: string
          default: ''
          description: Walrus metadata service name.
          x-walrus-ui:
            hidden: true
